import aiAutomationsImage from "../../images/ai-automations.png";
import aiCallAgentImage from "../../images/Ai-Call-Agent.jpg";
import { PROCESS_STEPS, SERVICES } from "./company";
import { getProjects } from "./projects";

const unsplash = (id, width = 1200) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${width}&q=80`;

const sharedImages = {
  serviceAi: unsplash("1677442136019-21780ecad995"),
  serviceCallAgent: aiCallAgentImage,
  serviceMobile: unsplash("1512941937669-90a1b58e7e9c"),
  serviceWeb: unsplash("1576153192396-180ecef2a715"),
  serviceSystem: unsplash("1551288049-bebda4e38f71"),
  serviceIt: unsplash("1629837093109-11325d6e7afd"),
  automationWorkflow: aiAutomationsImage,
  portfolioCta: unsplash("1542744173-8e7e53415bb0", 1400),
  processHero: unsplash("1532622785990-d2c36a76f5a6", 1400),
  processCta: unsplash("1507925921958-8a62f3d1a50d", 1400),
  contactHero: unsplash("1616587226960-4a03badbe8bf", 1400),
  contactCta: unsplash("1521791136064-7986c2920216", 1400),
};

const serviceImages = {
  brain: sharedImages.serviceAi,
  headset: sharedImages.serviceCallAgent,
  mobile: sharedImages.serviceMobile,
  globe: sharedImages.serviceWeb,
  cogs: sharedImages.serviceSystem,
  code: sharedImages.serviceIt,
};

const withServiceImages = (services) => services.map((service) => ({ ...service, image: serviceImages[service.icon] }));


export const SITE_CONTENT = {
  en: {
    locale: "en",
    direction: "ltr",
    navItems: [
      { id: "home", label: "Home" },
      { id: "services", label: "Services" },
      { id: "portfolio", label: "Portfolio" },
      { id: "process", label: "Process" },
      { id: "contact", label: "Contact" },
    ],
    socialLinks: [
      { id: "instagram", label: "Instagram", href: "https://www.instagram.com/queue.solutions/" },
      { id: "facebook", label: "Facebook", href: "https://www.facebook.com/profile.php?id=61585024646035" },
    ],
    siteDetails: {
      name: "Queue Solutions",
      email: "queuesolutions25@gmail.com",
      whatsappNumber: "+20 11 27435060",
      whatsappHref: "https://wa.me/201127435060",
      tagline: "Websites, systems, and AI that help businesses grow",
      shortTagline: "Web, systems, and AI for modern brands",
      description:
        "Queue Solutions helps businesses present themselves more credibly online, run more smoothly behind the scenes, and reduce repetitive work with practical automation.",
    },
    ui: {
      startProject: "Start a Project",
      contactUs: "Contact Us",
      viewPortfolio: "See Our Work",
      ourServices: "Our Services",
      discussService: "Talk About This Service",
      beginProject: "Start the Process",
      languageToggle: "العربية",
      languageToggleMobile: "Arabic",
      footerNavigate: "Navigate",
      footerConnect: "Connect",
      footerSummary: "Websites, custom systems, and AI automation for businesses in Egypt and the Gulf.",
      footerRights: "All rights reserved.",
      whatsappFloat: "Chat on WhatsApp",
      modal: {
        eyebrow: "Project Inquiry",
        title: "Tell us what you need help with",
        description:
          "Tell us what your business does, what is slowing you down, and what you want this project to improve.",
        name: "Your full name",
        businessName: "Business name",
        email: "Email (optional)",
        phone: "Phone number",
        phoneCountry: "Country code",
        whatsappQuestion: "Is this number on WhatsApp?",
        whatsappYes: "Yes, it has WhatsApp",
        whatsappYesHint: "We can reach you faster there if needed.",
        whatsappNo: "No, regular calls only",
        whatsappNoHint: "We will use normal calls and email instead.",
        whatsappRequired: "Choose whether this number has WhatsApp.",
        emailInvalid: "Enter a valid email address.",
        phoneInvalid: "Enter a valid phone number.",
        idea: "Project idea",
        cancel: "Cancel",
        submit: "Send Details",
        success: "Thank you. Your inquiry has been sent successfully.",
        successTitle: "Your form has been sent",
        successDescription: "Our team will review your details and reply within the next 24 hours.",
        successButton: "Close",
        emailSubject: "New Project Inquiry from",
        emailBodyTitle: "New Project Inquiry",
        emailName: "Name",
        emailEmail: "Email",
        emailPhone: "Phone",
        emailIdea: "Project Idea",
        notProvided: "Not provided",
        demoPrefix: "I would like a demo of",
        modeProject: "New project",
        modeAudit: "Digital audit",
        freeBadge: "Free",
        auditEyebrow: "Free Digital Audit",
        auditTitle: "Get a free review of your online presence",
        auditDescription:
          "Send us your website or social page and we will reply with a short, honest list of what is costing you customers and what to fix first. No obligation.",
        auditWebsite: "Website, Instagram, or Facebook link (optional)",
        auditIdea: "What would you like more of? (e.g. more bookings, more WhatsApp inquiries)",
        auditSubmit: "Request Free Audit",
        auditTag: "Free digital audit",
        auditWebsiteLabel: "Link",
        auditSubject: "Free digital audit request from",
      },
      contactCards: {
        emailTitle: "Business email",
        emailEyebrow: "Fast Reply",
        emailAction: "Send Email",
        whatsappTitle: "WhatsApp",
        whatsappEyebrow: "Available Now",
        whatsappBody: "Chat with us directly on WhatsApp.",
        formEyebrow: "Project Brief",
        formTitle: "Start with the form",
        formBody: "Share the main project details and we will contact you directly.",
        formAction: "Open project form",
      },
      contactWhy: "Why Businesses Contact Us",
      processSteps: "How the Work Moves",
      capabilities: "Capabilities",
      whyQueue: "Why Businesses Choose Queue",
      nextProject: "Your Next Project",
      readyToBegin: "Ready to Start?",
      getInTouch: "Let's Talk",
      resultLabel: "Outcome",
      visitProject: "Open live project",
      requestDemo: "Request a demo",
      live: "Live",
      viewCaseStudy: "Case study",
      backToPortfolio: "All projects",
      caseStudyEyebrow: "Case Study",
      challenge: "The challenge",
      solution: "What we built",
      before: "Before",
      after: "After",
      highlightsTitle: "Key features",
      screenshotsTitle: "Inside the product",
      watchDemo: "Watch the demo",
      industry: "Industry",
      platform: "Platform",
      builtWith: "Built with",
      client: "Client",
      nextCaseStudy: "Next project",
      testimonialsTitle: "What our clients say",
      pricing: {
        currency: "EGP",
        perYear: "/ year",
        oneTime: "one-time",
        popular: "Most popular",
        choose: "Get started",
        from: "From",
        seePricing: "See pricing",
        bookDemo: "Book a free demo",
        whatsappDemo: "Ask on WhatsApp",
        faqTitle: "Frequently asked questions",
      },
      audit: {
        eyebrow: "Free Digital Audit",
        title: "Not sure where to start? Get a free digital audit",
        description:
          "Send us your website or social page and we will tell you, honestly and for free, what is costing you customers and what to fix first.",
        action: "Get my free audit",
      },
      productsSection: {
        eyebrow: "Ready-Made Products",
        title: "Software you can start using this week",
        description: "Proven systems already running in real businesses, with clear prices and a free demo.",
        footerTitle: "Products",
      },
      phase: "Phase",
      stage: "Stage",
      step: "Step",
      of: "of",
      next: "Next",
      readyToLaunch: "Ready to launch",
      platforms: { web: "Website", webapp: "Web app", desktop: "Windows desktop" },
      filters: { all: "All work", web: "Web", desktop: "Desktop", ai: "AI" },
    },
    home: {
      heroTitleTop: "Where Your Ideas Come True",
      heroTitleAccent: "Queue Solutions",
      heroDescription:
        "One team for your website, your internal systems, and the AI automation that keeps the routine work moving.",
      heroCards: [
        { title: "Websites", description: "Clear, polished websites that build trust and turn interest into real inquiries." },
        { title: "Systems", description: "Dashboards and tools that keep the team aligned and the data in one place." },
        { title: "AI Automation", description: "Follow-up, reminders, and repeated admin handled automatically." },
      ],
    },
    services: {
      hero: {
        eyebrow: "Our Services",
        title: "Practical, polished solutions that move your business forward",
        mobileTitle: "Websites, systems, and automation",
        mobileDescription: "We help businesses look stronger and waste less time on repeated work.",
        description:
          "We help businesses look sharper, work faster, and stop losing time on repeated tasks that should already be handled.",
      },
      automationHighlight: {
        eyebrow: "Let automation carry the routine",
        title: "Repeated work runs on its own, so your attention stays on growth, service, and better ideas",
        mobileTitle: "Routine work runs itself",
        description:
          "Instead of your team replying manually, chasing people, copying details between tools, or updating the same task over and over, we build automation that keeps those steps moving in the background.",
        mobileDescription:
          "Replies, follow-up, reminders, and handoffs keep moving automatically while your team focuses on real work.",
        note:
          "You focus on clients, delivery, strategy, and growing the business. We stop the repeated work from stealing your attention.",
        mobileNote: "Less busywork. More time for growth.",
        chips: ["Reply faster", "Follow up automatically", "Reduce admin work", "Keep work moving"],
        mobilePointTitles: ["Instant lead replies", "No-chase follow-up", "Smart request routing", "More time back"],
        image: sharedImages.automationWorkflow,
        imageAlt: "Diagram of connected AI tools and automation workflows",
        points: [
          {
            title: "New leads hear back right away",
            description: "The moment someone fills in a form, they receive a reply and a clear next step before their interest cools.",
          },
          {
            title: "Follow-up happens without chasing",
            description: "Reminders, check-ins, and routine updates are sent automatically instead of depending on memory.",
          },
          {
            title: "The right person gets the task",
            description: "Requests are sorted and sent to sales, operations, or support with the right details already attached.",
          },
          {
            title: "Your team gets its time back",
            description: "Less copy-paste and fewer repeated checks means more room for delivery, sales, and creative thinking.",
          },
        ],
      },
      callAgentHighlight: {
        eyebrow: "AI call agent",
        title: "Turn missed calls into new clients with an AI agent that answers, explains, and captures the lead",
        mobileTitle: "Never miss a valuable call",
        description:
          "When someone calls and your team is busy, the opportunity should not disappear. We build AI call agents that answer instantly, explain your service clearly, collect the caller's details, and pass the conversation to your team.",
        mobileDescription: "The AI agent answers fast, explains your service, and sends your team the important details.",
        note: "The goal is simple: fewer missed opportunities, faster response, and a better first impression on every call.",
        mobileNote: "Missed calls become real opportunities.",
        chips: ["Answers instantly", "Explains the service", "Captures lead details", "Fewer missed opportunities"],
        mobilePointTitles: ["Calls answered fast", "Clear service intro", "Lead details captured", "Stronger first impression"],
        image: sharedImages.serviceCallAgent,
        imageAlt: "Customer support agent with a headset at an AI-assisted workstation",
        points: [
          {
            title: "Missed calls stop becoming lost leads",
            description: "Calls are answered even when your team is unavailable, so potential clients are never left waiting.",
          },
          {
            title: "Your service is explained clearly",
            description: "The agent answers common questions, explains the offer, and guides the caller to the right next step.",
          },
          {
            title: "Your team receives the key details",
            description: "Names, phone numbers, service interest, and call context are all captured automatically.",
          },
          {
            title: "It feels faster and more professional",
            description: "A quick answer on the first call builds trust and shows the business is organized from the start.",
          },
        ],
      },
      services: withServiceImages(SERVICES.en),
      capabilitiesTitle: "One partner for the customer-facing side and the operational side",
      capabilitiesMobileTitle: "One partner across the business",
      capabilitiesMobileDescription: "Your website, systems, and automation should all work together.",
      capabilitiesDescription:
        "The website, the workflow, and the internal system should feel like parts of the same business, not separate projects.",
      reasonsTitle: "Why businesses choose Queue",
      reasonsMobileTitle: "Why businesses choose us",
      reasonsMobileDescription: "The work has to look strong and solve a real business problem.",
      reasonsDescription: "We keep the work practical. The design needs to look strong, but it also needs to solve something real.",
      reasonsMobileTitles: ["Business-first thinking", "Easy to trust", "Useful technology", "One connected process"],
      reasons: [
        {
          title: "We start with the business problem",
          description: "Before we talk about features, we ask what is slowing the business down and what a better result looks like.",
        },
        {
          title: "We care about how it feels to use",
          description: "Strong design is not decoration. It makes the product easier to trust, understand, and use.",
        },
        {
          title: "We choose useful technology",
          description: "The stack should support the goal. We use modern tools where they bring speed, clarity, and reliability.",
        },
        {
          title: "We stay involved through delivery",
          description: "Strategy, design, build, launch, and refinement happen in one connected process instead of being passed around.",
        },
      ],
    },
    portfolio: {
      hero: {
        eyebrow: "Featured Work",
        title: "Real products we designed, built, and delivered",
        mobileTitle: "Real work, real clients",
        mobileDescription: "Websites, AI agents, and desktop systems running in real businesses.",
        description:
          "From online stores with AI stylists to desktop systems that run restaurants and clinics. Open any live project, or ask us for a demo of the desktop software.",
      },
      projects: getProjects("en"),
      cta: {
        eyebrow: "Your Next Project",
        title: "Want work like this for your business?",
        mobileTitle: "Want work like this?",
        mobileDescription: "Tell us what you need and we will suggest the right first step.",
        description:
          "Tell us what your business does and where it is getting stuck. We will suggest the right first step, whether that is a website, a system, or an AI agent.",
        image: sharedImages.portfolioCta,
        imageAlt: "Team presenting a project plan in a meeting room",
      },
    },
    process: {
      hero: {
        eyebrow: "How We Work",
        title: "A clear process that keeps momentum without losing quality",
        mobileTitle: "A process that stays clear",
        mobileDescription: "You always know what we are doing, what comes next, and why it matters.",
        description: "You always know what we are doing, what comes next, and what the work is meant to improve.",
        image: sharedImages.processHero,
        imageAlt: "Product planning session at a whiteboard",
        cards: [
          { title: "Clarity", text: "Everyone knows the goal before the build starts." },
          { title: "Momentum", text: "The work keeps moving without unnecessary detours." },
          { title: "Care", text: "Design and implementation stay aligned from start to finish." },
        ],
      },
      stepsTitle: "From first conversation to launch, the work stays clear",
      stepsMobileTitle: "From first call to launch",
      steps: PROCESS_STEPS.en,
      cta: {
        eyebrow: "Ready to Start?",
        title: "A good process matters because it protects the result",
        mobileTitle: "The process protects the result",
        mobileDescription: "A calm, well-run process leads to a stronger result.",
        description: "If the site feels calm and polished, the work behind it should feel the same way.",
        image: sharedImages.processCta,
        imageAlt: "Planning board with organized sticky notes",
      },
    },
    contact: {
      hero: {
        eyebrow: "Let's Talk",
        title: "Tell us what you want to improve",
        mobileTitle: "Tell us what to improve",
        mobileDescription: "Share the essentials and we will come back with the right next step.",
        description:
          "Whether you need a better website, a clearer internal system, or smarter automation, send us the essentials and we will come back with the right next step.",
        image: sharedImages.contactHero,
        imageAlt: "Client and consultant on a video call discussing a project",
      },
      whyTitle: "A useful first conversation, not a sales script",
      reasons: [
        "Clear advice based on where the business is today",
        "A realistic recommendation for the highest-impact next move",
        "A project direction that fits both the brand and the way the team works",
      ],
      cta: {
        eyebrow: "Project Brief",
        title: "Send the essentials and we will take it from there",
        mobileTitle: "Send the essentials",
        mobileDescription: "You do not need a perfect brief. Just send the important parts.",
        description:
          "You do not need a perfect brief. Just tell us what you do, what is frustrating right now, and what kind of result you want.",
        image: sharedImages.contactCta,
        imageAlt: "Business handshake after agreeing on a project",
      },
    },
  },
  ar: {
    locale: "ar",
    direction: "rtl",
    navItems: [
      { id: "home", label: "الرئيسية" },
      { id: "services", label: "خدماتنا" },
      { id: "portfolio", label: "أعمالنا" },
      { id: "process", label: "منهجية العمل" },
      { id: "contact", label: "تواصل معنا" },
    ],
    socialLinks: [
      { id: "instagram", label: "إنستجرام", href: "https://www.instagram.com/queue.solutions/" },
      { id: "facebook", label: "فيسبوك", href: "https://www.facebook.com/profile.php?id=61585024646035" },
    ],
    siteDetails: {
      name: "Queue Solutions",
      email: "queuesolutions25@gmail.com",
      whatsappNumber: "+20 11 27435060",
      whatsappHref: "https://wa.me/201127435060",
      tagline: "مواقع وأنظمة وحلول ذكاء اصطناعي تساعد الشركات على النمو",
      shortTagline: "مواقع وأنظمة وذكاء اصطناعي",
      description:
        "تساعد Queue Solutions الشركات على الظهور باحترافية على الإنترنت، وتنظيم العمل الداخلي، وتقليل المهام المتكررة من خلال أتمتة عملية.",
    },
    ui: {
      startProject: "ابدأ مشروعك",
      contactUs: "تواصل معنا",
      viewPortfolio: "شاهد أعمالنا",
      ourServices: "خدماتنا",
      discussService: "استفسر عن الخدمة",
      beginProject: "ابدأ الآن",
      languageToggle: "English",
      languageToggleMobile: "English",
      footerNavigate: "روابط سريعة",
      footerConnect: "تابعنا",
      footerSummary: "مواقع إلكترونية وأنظمة مخصصة وأتمتة بالذكاء الاصطناعي للشركات في مصر والخليج.",
      footerRights: "جميع الحقوق محفوظة.",
      whatsappFloat: "تحدث معنا على واتساب",
      modal: {
        eyebrow: "طلب مشروع",
        title: "أخبرنا بما تحتاجه",
        description: "عرّفنا بنشاطك، وبما يعطّل العمل حاليًا، وبالنتيجة التي تريد أن يحققها المشروع.",
        name: "الاسم بالكامل",
        businessName: "اسم الشركة أو النشاط",
        email: "البريد الإلكتروني (اختياري)",
        phone: "رقم الهاتف",
        phoneCountry: "كود الدولة",
        whatsappQuestion: "هل يتوفر واتساب على هذا الرقم؟",
        whatsappYes: "نعم، متاح على واتساب",
        whatsappYesHint: "سيساعدنا ذلك على التواصل معك بشكل أسرع.",
        whatsappNo: "لا، مكالمات هاتفية فقط",
        whatsappNoHint: "سنتواصل معك عبر الهاتف أو البريد الإلكتروني.",
        whatsappRequired: "يُرجى تحديد ما إذا كان الرقم متاحًا على واتساب.",
        emailInvalid: "يُرجى إدخال بريد إلكتروني صحيح.",
        phoneInvalid: "يُرجى إدخال رقم هاتف صحيح.",
        idea: "صف فكرة المشروع باختصار",
        cancel: "إلغاء",
        submit: "إرسال الطلب",
        success: "شكرًا لك، تم إرسال طلبك بنجاح.",
        successTitle: "تم استلام طلبك",
        successDescription: "سيراجع فريقنا التفاصيل ويتواصل معك خلال 24 ساعة.",
        successButton: "إغلاق",
        emailSubject: "طلب مشروع جديد من",
        emailBodyTitle: "طلب مشروع جديد",
        emailName: "الاسم",
        emailEmail: "البريد الإلكتروني",
        emailPhone: "الهاتف",
        emailIdea: "فكرة المشروع",
        notProvided: "غير متوفر",
        demoPrefix: "أرغب في عرض تجريبي لـ",
        modeProject: "مشروع جديد",
        modeAudit: "تقييم رقمي",
        freeBadge: "مجاني",
        auditEyebrow: "تقييم رقمي مجاني",
        auditTitle: "احصل على تقييم مجاني لحضورك الرقمي",
        auditDescription:
          "أرسل لنا رابط موقعك أو صفحتك على السوشيال ميديا، وسنرسل لك قائمة مختصرة وصريحة بما يفقدك العملاء وما يجب إصلاحه أولًا، دون أي التزام.",
        auditWebsite: "رابط الموقع أو إنستجرام أو فيسبوك (اختياري)",
        auditIdea: "ما الذي تريد زيادته؟ (مثل: حجوزات أكثر، استفسارات واتساب أكثر)",
        auditSubmit: "اطلب التقييم المجاني",
        auditTag: "تقييم رقمي مجاني",
        auditWebsiteLabel: "الرابط",
        auditSubject: "طلب تقييم رقمي مجاني من",
      },
      contactCards: {
        emailTitle: "البريد الإلكتروني",
        emailEyebrow: "رد سريع",
        emailAction: "أرسل رسالة",
        whatsappTitle: "واتساب",
        whatsappEyebrow: "متاح الآن",
        whatsappBody: "تواصل معنا مباشرة عبر واتساب.",
        formEyebrow: "تفاصيل المشروع",
        formTitle: "ابدأ بملء النموذج",
        formBody: "أرسل لنا أهم تفاصيل مشروعك، وسنتواصل معك مباشرة.",
        formAction: "افتح نموذج المشروع",
      },
      contactWhy: "لماذا يتواصل معنا العملاء",
      processSteps: "مراحل العمل",
      capabilities: "ما نقدمه",
      whyQueue: "لماذا Queue Solutions",
      nextProject: "مشروعك القادم",
      readyToBegin: "هل أنت مستعد للبدء؟",
      getInTouch: "لنتحدث",
      resultLabel: "النتيجة",
      visitProject: "زيارة المشروع",
      requestDemo: "اطلب عرضًا تجريبيًا",
      live: "مباشر",
      viewCaseStudy: "دراسة الحالة",
      backToPortfolio: "كل المشاريع",
      caseStudyEyebrow: "دراسة حالة",
      challenge: "التحدي",
      solution: "ما الذي بنيناه",
      before: "قبل",
      after: "بعد",
      highlightsTitle: "أبرز المزايا",
      screenshotsTitle: "من داخل البرنامج",
      watchDemo: "شاهد العرض",
      industry: "المجال",
      platform: "المنصة",
      builtWith: "التقنيات",
      client: "العميل",
      nextCaseStudy: "المشروع التالي",
      testimonialsTitle: "آراء عملائنا",
      pricing: {
        currency: "جنيه",
        perYear: "/ سنويًا",
        oneTime: "دفعة واحدة",
        popular: "الأكثر طلبًا",
        choose: "ابدأ الآن",
        from: "يبدأ من",
        seePricing: "عرض الأسعار",
        bookDemo: "احجز عرضًا تجريبيًا مجانيًا",
        whatsappDemo: "اسألنا على واتساب",
        faqTitle: "الأسئلة الشائعة",
      },
      audit: {
        eyebrow: "تقييم رقمي مجاني",
        title: "لا تعرف من أين تبدأ؟ احصل على تقييم رقمي مجاني",
        description:
          "أرسل لنا رابط موقعك أو صفحتك، وسنخبرك بصراحة ومجانًا بما يفقدك العملاء وما يجب إصلاحه أولًا.",
        action: "احصل على تقييمك المجاني",
      },
      productsSection: {
        eyebrow: "منتجات جاهزة",
        title: "برامج يمكنك البدء في استخدامها هذا الأسبوع",
        description: "أنظمة مجرّبة تعمل بالفعل في شركات حقيقية، بأسعار واضحة وعرض تجريبي مجاني.",
        footerTitle: "منتجاتنا",
      },
      phase: "المرحلة",
      stage: "المرحلة",
      step: "الخطوة",
      of: "من",
      next: "التالي",
      readyToLaunch: "جاهز للإطلاق",
      platforms: { web: "موقع إلكتروني", webapp: "تطبيق ويب", desktop: "برنامج ويندوز" },
      filters: { all: "كل الأعمال", web: "مواقع وتطبيقات ويب", desktop: "برامج سطح المكتب", ai: "ذكاء اصطناعي" },
    },
    home: {
      heroTitleTop: "حيث تتحول أفكارك إلى واقع",
      heroTitleAccent: "Queue Solutions",
      heroDescription: "فريق واحد لموقعك الإلكتروني وأنظمتك الداخلية، وللأتمتة الذكية التي تُنجز المهام الروتينية عنك.",
      heroCards: [
        { title: "المواقع الإلكترونية", description: "مواقع واضحة وأنيقة تكسب ثقة الزائر وتحوّل اهتمامه إلى طلب فعلي." },
        { title: "الأنظمة", description: "لوحات تحكم وأدوات تجمع بيانات فريقك في مكان واحد." },
        { title: "الأتمتة الذكية", description: "المتابعة والتذكيرات والمهام الإدارية المتكررة تتم تلقائيًا." },
      ],
    },
    services: {
      hero: {
        eyebrow: "خدماتنا",
        title: "حلول عملية ومتقنة تدفع أعمالك إلى الأمام",
        mobileTitle: "مواقع وأنظمة وأتمتة",
        description: "نساعد الشركات على الظهور بصورة أقوى، والعمل بسرعة أكبر، والتخلص من المهام المتكررة التي تستهلك وقت الفريق.",
        mobileDescription: "حضور أقوى، وعمل أسرع، ووقت أقل يضيع في المهام المتكررة.",
      },
      automationHighlight: {
        eyebrow: "دع الأتمتة تتولى الروتين",
        title: "المهام المتكررة تُنجز تلقائيًا، ويبقى تركيزك على النمو وخدمة العملاء والأفكار الجديدة",
        mobileTitle: "المهام المتكررة تُنجز تلقائيًا",
        description:
          "بدلًا من أن يرد فريقك يدويًا، ويلاحق العملاء، وينقل البيانات بين الأدوات، ويكرر المهمة نفسها كل يوم، نبني أتمتة تُنجز هذه الخطوات في الخلفية.",
        mobileDescription: "الردود والمتابعة والتذكيرات وتسليم المهام تتم تلقائيًا بينما يركز فريقك على العمل الفعلي.",
        note: "أنت تركز على العملاء والتنفيذ والاستراتيجية، ونحن نضمن ألا تستنزف المهام المتكررة وقتك.",
        mobileNote: "مهام روتينية أقل، ووقت أكبر للنمو.",
        chips: ["ردود أسرع", "متابعة تلقائية", "أعمال إدارية أقل", "سير عمل لا يتوقف"],
        mobilePointTitles: ["رد فوري على العملاء", "متابعة دون عناء", "توجيه ذكي للطلبات", "وقت أكثر لفريقك"],
        image: sharedImages.automationWorkflow,
        imageAlt: "مخطط لأدوات ذكاء اصطناعي وسير عمل مؤتمت مترابط",
        points: [
          {
            title: "العميل الجديد يتلقى ردًا فوريًا",
            description: "بمجرد أن يملأ العميل النموذج، تصله رسالة واضحة بالخطوة التالية قبل أن يفتر اهتمامه.",
          },
          {
            title: "متابعة دون ملاحقة",
            description: "التذكيرات ورسائل المتابعة وتحديثات الحالة تُرسل تلقائيًا، دون الاعتماد على الذاكرة.",
          },
          {
            title: "كل طلب يصل إلى الشخص المناسب",
            description: "تُفرز الطلبات وتُحوَّل إلى المبيعات أو التشغيل أو الدعم، ومعها كل التفاصيل اللازمة.",
          },
          {
            title: "فريقك يستعيد وقته",
            description: "نسخ ولصق أقل ومراجعات متكررة أقل، يعني وقتًا أكبر للمبيعات والتنفيذ والإبداع.",
          },
        ],
      },
      callAgentHighlight: {
        eyebrow: "وكيل مكالمات ذكي",
        title: "حوّل المكالمات الفائتة إلى عملاء جدد بوكيل ذكي يرد ويشرح ويسجّل بيانات المتصل",
        mobileTitle: "لا تفوّت أي مكالمة مهمة",
        description:
          "عندما يتصل عميل وفريقك مشغول، لا ينبغي أن تضيع الفرصة. نبني وكلاء مكالمات بالذكاء الاصطناعي يردون فورًا، ويشرحون خدمتك بوضوح، ويسجلون بيانات المتصل، ثم يسلّمونها لفريقك.",
        mobileDescription: "وكيل يرد على المكالمات حين يكون فريقك مشغولًا، ويسلّمه البيانات المهمة.",
        note: "الهدف واضح: فرص ضائعة أقل، واستجابة أسرع، وانطباع أول احترافي مع كل مكالمة.",
        mobileNote: "المكالمات الفائتة تتحول إلى فرص حقيقية.",
        chips: ["رد فوري", "شرح واضح للخدمة", "تسجيل بيانات العميل", "فرص ضائعة أقل"],
        mobilePointTitles: ["رد سريع على كل مكالمة", "تعريف واضح بالخدمة", "تسجيل بيانات العميل", "انطباع أول أقوى"],
        image: sharedImages.serviceCallAgent,
        imageAlt: "موظفة خدمة عملاء بسماعة رأس أمام شاشة مدعومة بالذكاء الاصطناعي",
        points: [
          {
            title: "المكالمة الفائتة لا تعني عميلًا ضائعًا",
            description: "يتم الرد على كل مكالمة حتى عندما يكون فريقك غير متاح، فلا يبقى أي عميل محتمل دون رد.",
          },
          {
            title: "خدمتك تُشرح بشكل صحيح",
            description: "يجيب الوكيل عن الأسئلة الشائعة، ويعرّف بخدمتك، ويوجّه المتصل إلى الخطوة المناسبة.",
          },
          {
            title: "فريقك يستلم التفاصيل المهمة",
            description: "الاسم ورقم الهاتف والخدمة المطلوبة وسياق المكالمة تُسجَّل جميعها تلقائيًا.",
          },
          {
            title: "انطباع أول احترافي",
            description: "الرد السريع من المكالمة الأولى يبني الثقة ويُظهر نشاطك منظمًا منذ البداية.",
          },
        ],
      },
      services: withServiceImages(SERVICES.ar),
      capabilitiesTitle: "شريك واحد لواجهة أعمالك أمام العملاء ولعملياتك الداخلية",
      capabilitiesMobileTitle: "شريك واحد لكل احتياجاتك",
      capabilitiesMobileDescription: "الموقع والنظام والأتمتة يجب أن تعمل معًا.",
      capabilitiesDescription:
        "الموقع وسير العمل والنظام الداخلي ينبغي أن تبدو أجزاءً من كيان واحد، لا مشاريع منفصلة.",
      reasonsTitle: "لماذا تختارنا الشركات",
      reasonsMobileTitle: "لماذا تختارنا الشركات",
      reasonsMobileDescription: "العمل يجب أن يبدو قويًا ويحل مشكلة حقيقية.",
      reasonsDescription: "نحرص على أن يكون العمل عمليًا: التصميم يجب أن يكون قويًا، لكنه يجب أيضًا أن يحل مشكلة حقيقية.",
      reasonsMobileTitles: ["نفكر بعقلية صاحب العمل", "نتائج تبني الثقة", "تقنيات مناسبة للهدف", "مسار عمل متكامل"],
      reasons: [
        {
          title: "نبدأ من مشكلة العمل",
          description: "قبل الحديث عن الخصائص، نسأل: ما الذي يبطئ عملك؟ وكيف تبدو النتيجة الأفضل؟",
        },
        {
          title: "نهتم بتجربة الاستخدام",
          description: "التصميم الجيد ليس زينة؛ بل هو ما يجعل المنتج أسهل في الفهم والاستخدام وأجدر بالثقة.",
        },
        {
          title: "نختار التقنية المناسبة",
          description: "التقنية وسيلة لتحقيق الهدف، لذلك نستخدم الأدوات الحديثة حيث تضيف سرعة ووضوحًا وموثوقية.",
        },
        {
          title: "نرافقك حتى التسليم وما بعده",
          description: "الاستراتيجية والتصميم والتطوير والإطلاق والتحسين تتم في مسار واحد متصل، دون تشتت بين أطراف متعددة.",
        },
      ],
    },
    portfolio: {
      hero: {
        eyebrow: "أعمال مختارة",
        title: "منتجات حقيقية صممناها وطورناها وسلّمناها",
        mobileTitle: "أعمال حقيقية لعملاء حقيقيين",
        description:
          "من متاجر إلكترونية بمساعد تنسيق ذكي، إلى أنظمة سطح مكتب تدير المطاعم والعيادات. افتح أي مشروع مباشر، أو اطلب عرضًا تجريبيًا لبرامجنا.",
        mobileDescription: "مواقع ووكلاء ذكاء اصطناعي وأنظمة تعمل في شركات حقيقية.",
      },
      projects: getProjects("ar"),
      cta: {
        eyebrow: "مشروعك القادم",
        title: "هل تريد عملًا بهذا المستوى لنشاطك؟",
        mobileTitle: "هل تريد عملًا بهذا المستوى؟",
        description:
          "أخبرنا عن نشاطك وأين يتعثر العمل حاليًا، وسنقترح عليك الخطوة الأولى المناسبة، سواء كانت موقعًا أو نظامًا أو وكيلًا ذكيًا.",
        mobileDescription: "أخبرنا بما تحتاجه، وسنقترح عليك الخطوة الأولى المناسبة.",
        image: sharedImages.portfolioCta,
        imageAlt: "فريق يعرض خطة مشروع في قاعة اجتماعات",
      },
    },
    process: {
      hero: {
        eyebrow: "منهجية العمل",
        title: "مراحل واضحة، تعرف فيها أين نحن وإلى أين نتجه",
        mobileTitle: "مراحل واضحة منذ اليوم الأول",
        description: "لا مفاجآت ولا وعود غامضة. في كل مرحلة تعرف ما الذي ننفذه الآن، وما الخطوة التالية، وكيف ستفيد نشاطك.",
        mobileDescription: "تعرف دائمًا ما ننفذه الآن وما الخطوة التالية.",
        image: sharedImages.processHero,
        imageAlt: "جلسة تخطيط لمشروع أمام سبورة بيضاء",
        cards: [
          { title: "الوضوح", text: "الهدف متفق عليه قبل أن نبدأ التنفيذ." },
          { title: "الاستمرارية", text: "العمل يتقدم بثبات دون توقف أو تشتت." },
          { title: "الإتقان", text: "التصميم والتنفيذ يسيران معًا من البداية إلى النهاية." },
        ],
      },
      stepsTitle: "من أول محادثة حتى الإطلاق، الصورة واضحة",
      stepsMobileTitle: "من أول محادثة حتى الإطلاق",
      steps: PROCESS_STEPS.ar,
      cta: {
        eyebrow: "هل أنت مستعد للبدء؟",
        title: "المنهجية الجيدة هي ما يحمي النتيجة",
        mobileTitle: "المنهجية تحمي النتيجة",
        description: "نحن لا نبيع خطوات عمل، بل نتيجة تلمسها في نشاطك. لنتحدث عما تحتاجه فعلًا.",
        mobileDescription: "نتيجة تلمسها في نشاطك، لا مجرد خطوات عمل.",
        image: sharedImages.processCta,
        imageAlt: "لوحة تخطيط بملاحظات لاصقة منظمة",
      },
    },
    contact: {
      hero: {
        eyebrow: "تواصل معنا",
        title: "أخبرنا عن نشاطك، وسنعطيك رأيًا صريحًا من البداية",
        mobileTitle: "أخبرنا عن نشاطك",
        description:
          "لا تحتاج إلى خطة مكتملة. أرسل لنا ما لديك، وإذا وجدنا طريقًا أبسط أو أقل تكلفة فسنخبرك به.",
        mobileDescription: "أرسل لنا ما لديك، وسنقترح عليك الطريق الأنسب.",
        image: sharedImages.contactHero,
        imageAlt: "عميل ومستشار في مكالمة فيديو لمناقشة مشروع",
      },
      whyTitle: "محادثة أولى مفيدة، لا عرض مبيعات",
      reasons: [
        "نصيحة واضحة تناسب المرحلة التي يمر بها نشاطك",
        "توصية واقعية بالخطوة الأكثر تأثيرًا",
        "اتجاه عمل يناسب علامتك التجارية وطريقة عمل فريقك",
      ],
      cta: {
        eyebrow: "لنتحدث",
        title: "لنصنع معًا شيئًا يستحق",
        mobileTitle: "لنصنع معًا شيئًا يستحق",
        description: "أرسل تفاصيل مشروعك، وسنعود إليك بخطوة واضحة يمكنك البدء بها، حتى لو قررت ألا تعمل معنا.",
        mobileDescription: "أرسل تفاصيلك، وسنعود إليك بخطوة واضحة.",
        image: sharedImages.contactCta,
        imageAlt: "مصافحة عمل بعد الاتفاق على مشروع",
      },
    },
  },
};
