// Plain data (no Vite imports) so scripts/prerender.mjs can read it at build time too.
// MolarBear × IDC 2026 campaign: free 14-day trial, installer gated behind a short lead form.
//
// Facts this copy relies on (keep them true): MolarBear is a Windows desktop app; an unlicensed
// installation runs fully for 14 days from its first launch, then stops saving new records until
// a licence is activated (data stays on the computer). No payment details are collected.

// Hosted on this site so the link stays stable. Replace the file (same name) when a new version ships.
export const TRIAL_DOWNLOAD = {
  url: "/downloads/MolarBear-Setup.exe",
  fileName: "MolarBear-Setup.exe",
  version: "1.30.0",
  sizeMb: 42,
  days: 14,
};

export const TRIAL_COPY = {
  en: {
    seoTitle: "MolarBear: 14 Days Free | Dental Clinic Software | IDC 2026 Offer",
    seoDescription:
      "Try MolarBear dental clinic software free for 14 days. Appointments, patient flow, dental chart, X-rays, and payments in one Windows app. No credit card required.",
    ribbon: "IDC 2026 offer: try MolarBear dental software free for 14 days",
    ribbonCta: "Start my free trial",
    headlineTop: "14 days free",
    headlineBottom: "with MolarBear",
    subheadline: "A simpler way to manage your dental clinic.",
    description: "Manage your appointments, organize your patient flow, and keep your clinic running smoothly from one place.",
    cta: "Start my free trial",
    noCard: "No credit card required.",
    idcTitle: "IDC 2026 special offer",
    idcText: "Get 14 days of MolarBear free.",
    idcDates: "7–9 October 2026",
    watchDemo: "Watch the 90-second demo",
    videoKicker: "See it in action",
    videoTitle: "MolarBear in 90 seconds",
    videoText: "Appointments, the dental chart, patient files and payments. See how a full clinic day runs from one screen.",
    videoCaption: "Real MolarBear screens · 1:28",
    videoEndTitle: "Like what you saw?",
    videoEndText: "Try it in your clinic free for 14 days.",
    replay: "Watch again",
    closeVideo: "Close video",
    formTitle: "Start your 14-day free trial",
    fields: {
      name: "Full name",
      email: "Email address",
      phone: "Mobile number",
      clinic: "Clinic name",
      city: "City",
      optional: "optional",
    },
    placeholders: { name: "Dr. Ahmed Hassan", clinic: "Smile Dental Clinic", city: "Cairo" },
    socialTitle: "Want to stay connected with Queue Solutions?",
    socialFacebook: "Follow us on Facebook",
    socialInstagram: "Follow us on Instagram",
    socialHint: "Opens our page in a new tab.",
    submit: "Start my free trial",
    submitting: "Preparing your trial...",
    errors: {
      name: "Enter your full name.",
      email: "Enter a valid email address.",
      phone: "Enter a valid mobile number.",
      clinic: "Enter your clinic name.",
      submit: "Something went wrong. Please try again, or message us on WhatsApp.",
    },
    successTitle: "Your 14-day free trial is ready!",
    successText: "Your download has started. Install MolarBear on your clinic computer to begin.",
    downloadButton: "Download MolarBear",
    successFacts: ["Trial duration: 14 days", "No payment required to start", "Windows 10 or 11"],
    stepsTitle: "Install in 3 steps",
    steps: [
      "Open MolarBear-Setup.exe and follow the installer.",
      "If Windows shows a blue SmartScreen message, click \"More info\" then \"Run anyway\".",
      "Open MolarBear. Your 14 days start the first time you open it.",
    ],
    needHelp: "Need help installing? Message us on WhatsApp",
    whatsappText: "Hello, I downloaded the MolarBear free trial and would like help setting it up.",
    fileInfo: "Windows 10 or 11",
    pcNote: "MolarBear runs on Windows PCs. On a phone? We'll send the download link to your email and WhatsApp.",
    pcOnlyTitle: "Download it on your clinic computer",
    pcOnlyText: "MolarBear must be downloaded and installed on a Windows PC (Windows 10 or 11). It does not run on phones.",
    getLinkTitle: "Get the download link on your PC:",
    emailSending: "Sending the download link to {email}...",
    emailSent: "Done! We emailed the download link to {email}. Open it on your clinic computer.",
    emailButton: "Email the link to {email}",
    pcEmailSent: "We also emailed the download link to {email}, so you can download it again any time.",
    whatsappSelf: "Send the link to my WhatsApp",
    copyLink: "Copy link",
    linkCopied: "Link copied",
    downloadAnyway: "Download on this device anyway",
    shareText: "MolarBear download link (open it on your Windows PC): {link}",
    mailSubject: "Your MolarBear download link",
    mailBody: "Open this link on your clinic's Windows computer to download MolarBear:\n{link}\n\nYour 14-day free trial starts the first time you open the app.",
    featuresTitle: "What can MolarBear do for your clinic?",
    features: [
      { icon: "calendar", title: "Appointments", text: "Organize your appointments and keep your schedule under control." },
      { icon: "users", title: "Patient flow", text: "Keep track of patients throughout their clinic journey." },
      { icon: "desktop", title: "Clinic management", text: "Manage your clinic from one organized system." },
      { icon: "chart", title: "Stay organized", text: "Keep important clinic information in one place." },
    ],
    howTitle: "Start in 3 simple steps",
    how: [
      { title: "Sign up", text: "Enter your basic information." },
      { title: "Start your trial", text: "Download MolarBear and install it on your clinic computer." },
      { title: "Run your clinic", text: "Try it for 14 days and see how it fits your workflow." },
    ],
    whyTitle: "Don't just hear about it. Try it.",
    whyText: ["Your clinic is different.", "Your workflow is different.", "That's why we're giving you 14 days to experience MolarBear for yourself."],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "Is the trial really free?", a: "Yes. You download the full version of MolarBear and use every feature for 14 days at no cost." },
      { q: "How long is the trial?", a: "14 days, counted from the first time you open MolarBear on your computer." },
      { q: "Do I need a credit card?", a: "No. You only fill in the short form above. No payment details are requested." },
      {
        q: "What happens after 14 days?",
        a: "MolarBear stops saving new records until you activate a licence. Your data stays on your computer. Choose a plan, starting from EGP 15,000 per year, and you continue exactly where you left off.",
      },
      { q: "Can I use MolarBear on my phone?", a: "No. MolarBear is a Windows desktop app for your clinic computers (Windows 10 or 11)." },
      { q: "Is MolarBear only for dentists?", a: "Yes. It is built specifically for dental clinics, from a solo dentist to clinics with several doctors." },
    ],
    finalTitle: "Ready to try MolarBear?",
    finalText: "Get your first 14 days free.",
    byline: "MolarBear by Queue Solutions",
    seePlans: "See plans after the trial",
    otherLanguage: "عربي",
  },
  ar: {
    seoTitle: "MolarBear مجانًا لمدة 14 يومًا | برنامج إدارة عيادات الأسنان | عرض IDC 2026",
    seoDescription:
      "جرّب برنامج MolarBear لإدارة عيادات الأسنان مجانًا لمدة 14 يومًا: المواعيد وسير المرضى ومخطط الأسنان والأشعة والمدفوعات في برنامج ويندوز واحد، دون بطاقة ائتمان.",
    ribbon: "عرض IDC 2026: جرّب برنامج MolarBear لعيادات الأسنان مجانًا لمدة 14 يومًا",
    ribbonCta: "ابدأ تجربتك المجانية",
    headlineTop: "14 يومًا مجانًا",
    headlineBottom: "مع MolarBear",
    subheadline: "طريقة أبسط لإدارة عيادة الأسنان.",
    description: "نظّم مواعيدك، وتابع سير المرضى داخل العيادة، وأدِر عيادتك بسلاسة من مكان واحد.",
    cta: "ابدأ تجربتي المجانية",
    noCard: "لا حاجة إلى بطاقة ائتمان.",
    idcTitle: "عرض خاص بمناسبة IDC 2026",
    idcText: "احصل على 14 يومًا من MolarBear مجانًا.",
    idcDates: "7–9 أكتوبر 2026",
    watchDemo: "شاهد العرض في 90 ثانية",
    videoKicker: "شاهده وهو يعمل",
    videoTitle: "MolarBear في 90 ثانية",
    videoText: "المواعيد، ومخطط الأسنان، وملفات المرضى، والمدفوعات. شاهد كيف يُدار يوم العيادة بالكامل من شاشة واحدة.",
    videoCaption: "شاشات حقيقية من MolarBear · 1:28",
    videoEndTitle: "أعجبك ما رأيت؟",
    videoEndText: "جرّبه في عيادتك مجانًا لمدة 14 يومًا.",
    replay: "شاهد مرة أخرى",
    closeVideo: "إغلاق الفيديو",
    formTitle: "ابدأ تجربتك المجانية لمدة 14 يومًا",
    fields: {
      name: "الاسم بالكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الموبايل",
      clinic: "اسم العيادة",
      city: "المدينة",
      optional: "اختياري",
    },
    placeholders: { name: "د. أحمد حسن", clinic: "عيادة سمايل لطب الأسنان", city: "القاهرة" },
    socialTitle: "هل تود متابعة Queue Solutions؟",
    socialFacebook: "تابعنا على فيسبوك",
    socialInstagram: "تابعنا على إنستجرام",
    socialHint: "تُفتح صفحتنا في نافذة جديدة.",
    submit: "ابدأ تجربتي المجانية",
    submitting: "جارٍ تجهيز تجربتك...",
    errors: {
      name: "يُرجى إدخال الاسم بالكامل.",
      email: "يُرجى إدخال بريد إلكتروني صحيح.",
      phone: "يُرجى إدخال رقم موبايل صحيح.",
      clinic: "يُرجى إدخال اسم العيادة.",
      submit: "حدث خطأ. حاول مرة أخرى أو راسلنا على واتساب.",
    },
    successTitle: "تجربتك المجانية لمدة 14 يومًا جاهزة!",
    successText: "بدأ التحميل. ثبّت MolarBear على جهاز العيادة لتبدأ.",
    downloadButton: "تحميل MolarBear",
    successFacts: ["مدة التجربة: 14 يومًا", "لا يلزم أي دفع للبدء", "ويندوز 10 أو 11"],
    stepsTitle: "التثبيت في 3 خطوات",
    steps: [
      "افتح ملف MolarBear-Setup.exe واتبع خطوات التثبيت.",
      "إذا ظهرت رسالة ويندوز الزرقاء (SmartScreen)، اضغط «More info» ثم «Run anyway».",
      "افتح MolarBear. تبدأ الأيام الـ 14 من أول مرة تفتح فيها البرنامج.",
    ],
    needHelp: "تحتاج مساعدة في التثبيت؟ راسلنا على واتساب",
    whatsappText: "مرحبًا، قمت بتحميل النسخة التجريبية من MolarBear وأحتاج مساعدة في تشغيلها.",
    fileInfo: "ويندوز 10 أو 11",
    pcNote: "يعمل MolarBear على أجهزة الكمبيوتر بنظام ويندوز. تستخدم الموبايل؟ سنرسل رابط التحميل إلى بريدك وواتساب.",
    pcOnlyTitle: "حمّله على كمبيوتر العيادة",
    pcOnlyText: "يجب تحميل MolarBear وتثبيته على كمبيوتر بنظام ويندوز (10 أو 11). البرنامج لا يعمل على الموبايل.",
    getLinkTitle: "احصل على رابط التحميل على الكمبيوتر:",
    emailSending: "جارٍ إرسال رابط التحميل إلى {email}...",
    emailSent: "تم! أرسلنا رابط التحميل إلى {email}. افتحه على كمبيوتر العيادة.",
    emailButton: "أرسل الرابط إلى {email}",
    pcEmailSent: "أرسلنا رابط التحميل أيضًا إلى {email}، لتتمكن من تحميله مرة أخرى في أي وقت.",
    whatsappSelf: "أرسل الرابط إلى واتساب الخاص بي",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط",
    downloadAnyway: "التحميل على هذا الجهاز على أي حال",
    shareText: "رابط تحميل MolarBear (افتحه على كمبيوتر ويندوز): {link}",
    mailSubject: "رابط تحميل MolarBear",
    mailBody: "افتح هذا الرابط على كمبيوتر العيادة (ويندوز) لتحميل MolarBear:\n{link}\n\nتبدأ فترة التجربة المجانية (14 يومًا) من أول مرة تفتح فيها البرنامج.",
    featuresTitle: "ماذا يقدم MolarBear لعيادتك؟",
    features: [
      { icon: "calendar", title: "المواعيد", text: "نظّم مواعيدك وحافظ على جدولك تحت السيطرة." },
      { icon: "users", title: "سير المرضى", text: "تابع كل مريض خلال رحلته داخل العيادة." },
      { icon: "desktop", title: "إدارة العيادة", text: "أدِر عيادتك من نظام واحد منظم." },
      { icon: "chart", title: "تنظيم أفضل", text: "احتفظ بكل معلومات العيادة المهمة في مكان واحد." },
    ],
    howTitle: "ابدأ في 3 خطوات بسيطة",
    how: [
      { title: "سجّل بياناتك", text: "أدخل بياناتك الأساسية." },
      { title: "ابدأ التجربة", text: "حمّل MolarBear وثبّته على جهاز العيادة." },
      { title: "أدِر عيادتك", text: "جرّبه لمدة 14 يومًا وشاهد كيف يناسب طريقة عملك." },
    ],
    whyTitle: "لا تكتفِ بالسماع عنه. جرّبه.",
    whyText: ["عيادتك مختلفة.", "وطريقة عملك مختلفة.", "لذلك نمنحك 14 يومًا لتجرّب MolarBear بنفسك."],
    faqTitle: "الأسئلة الشائعة",
    faq: [
      { q: "هل التجربة مجانية فعلًا؟", a: "نعم. تحمّل النسخة الكاملة من MolarBear وتستخدم كل مزاياها لمدة 14 يومًا دون أي تكلفة." },
      { q: "ما مدة التجربة؟", a: "14 يومًا، تُحسب من أول مرة تفتح فيها MolarBear على جهازك." },
      { q: "هل أحتاج إلى بطاقة ائتمان؟", a: "لا. تملأ النموذج القصير أعلاه فقط، ولا نطلب أي بيانات دفع." },
      {
        q: "ماذا يحدث بعد 14 يومًا؟",
        a: "يتوقف MolarBear عن حفظ سجلات جديدة حتى تفعّل الترخيص، وتبقى بياناتك محفوظة على جهازك. اختر باقة تبدأ من 15,000 جنيه سنويًا، وتكمل من حيث توقفت.",
      },
      { q: "هل يمكنني استخدام MolarBear على الموبايل؟", a: "لا. MolarBear برنامج سطح مكتب يعمل على أجهزة العيادة بنظام ويندوز 10 أو 11." },
      { q: "هل MolarBear مخصص لأطباء الأسنان فقط؟", a: "نعم. صُمم خصيصًا لعيادات الأسنان، من الطبيب المستقل حتى العيادات متعددة الأطباء." },
    ],
    finalTitle: "هل أنت مستعد لتجربة MolarBear؟",
    finalText: "احصل على أول 14 يومًا مجانًا.",
    byline: "MolarBear من Queue Solutions",
    seePlans: "الباقات بعد فترة التجربة",
    otherLanguage: "English",
  },
};
