// Plain data (no Vite imports) so scripts/prerender.mjs can read it at build time too.
// MolarBear × IDC 2026 campaign: free 14-day trial, installer gated behind a short lead form.
//
// Facts this copy relies on (keep them true): MolarBear is a Windows desktop app; an unlicensed
// installation runs fully for 14 days from its first launch, then stops saving new records until
// a licence is activated (data stays on the computer). No payment details are collected.

// Hosted on this site so the link stays stable. Replace the file (same name) when a new version ships.
export const TRIAL_DOWNLOAD = {
  url: "/downloads/MolarBear-Setup.exe",
  fileName: "MolarBear-Setup.exe",
  version: "1.28.2",
  sizeMb: 42,
  days: 14,
};

export const TRIAL_COPY = {
  en: {
    seoTitle: "MolarBear: 14 Days Free | Dental Clinic Software | IDC 2026 Offer",
    seoDescription:
      "Try MolarBear dental clinic software free for 14 days. Appointments, patient flow, dental chart, X-rays, and payments in one Windows app. No credit card required.",
    ribbon: "IDC 2026 offer: try MolarBear dental software free for 14 days",
    ribbonCta: "Start my free trial",
    headlineTop: "14 days free",
    headlineBottom: "with MolarBear",
    heroBadge: "IDC 2026 special offer",
    heroKicker: "Try MolarBear",
    heroOffer: "14 days free",
    subheadline: "Dental clinic management made simpler.",
    description:
      "Manage your patients, appointments, dental records, payments, inventory and daily clinic workflow from one place.",
    cta: "Start my free trial",
    ctaNote: "14 days free • No credit card required",
    noCard: "No credit card required.",
    idcTitle: "IDC 2026 special offer",
    idcText: "Get 14 days of MolarBear free.",
    idcDates: "7–9 October 2026",
    formTitle: "Get your 14-day free trial",
    formSubtitle: "Enter your details to start using MolarBear.",
    fields: {
      name: "Full name",
      email: "Email address",
      phone: "Mobile number",
      clinic: "Clinic name",
      city: "City",
      optional: "optional",
    },
    placeholders: { name: "Dr. Ahmed Hassan", clinic: "Smile Dental Clinic", city: "Cairo" },
    socialTitle: "Stay connected",
    socialText: "Follow Queue Solutions for MolarBear updates, new features and offers.",
    socialFacebook: "Follow us on Facebook",
    socialInstagram: "Follow us on Instagram",
    socialHint: "Opens our page in a new tab.",
    submit: "Start my free trial",
    submitting: "Preparing your trial...",
    errors: {
      name: "Enter your full name.",
      email: "Enter a valid email address.",
      phone: "Enter a valid mobile number.",
      clinic: "Enter your clinic name.",
      submit: "Something went wrong. Please try again, or message us on WhatsApp.",
    },
    successTitle: "Your 14-day free trial is ready!",
    successText: "Your download has started. Install MolarBear on your clinic computer to begin.",
    downloadButton: "Download MolarBear",
    successFacts: ["Trial duration: 14 days", "No payment required to start", "Windows 10 or 11"],
    stepsTitle: "Install in 3 steps",
    steps: [
      "Open MolarBear-Setup.exe and follow the installer.",
      "If Windows shows a blue SmartScreen message, click \"More info\" then \"Run anyway\".",
      "Open MolarBear. Your 14 days start the first time you open it.",
    ],
    needHelp: "Need help installing? Message us on WhatsApp",
    whatsappText: "Hello, I downloaded the MolarBear free trial and would like help setting it up.",
    fileInfo: "Windows 10 or 11",
    featuresTitle: "What can MolarBear do for your clinic?",
    features: [
      { icon: "patients", title: "Patients", text: "Keep patient information organized and easy to access." },
      { icon: "calendar", title: "Appointments", text: "Manage your schedule and upcoming visits." },
      { icon: "tooth", title: "Dental chart", text: "Keep clinical information connected to the patient." },
      { icon: "xray", title: "X-rays & records", text: "Keep clinical files organized and accessible." },
      { icon: "payments", title: "Payments", text: "Track payments and clinic financial information." },
      { icon: "inventory", title: "Inventory", text: "Keep track of clinic supplies and inventory." },
    ],
    howTitle: "Start in 3 simple steps",
    how: [
      { title: "Sign up", text: "Enter your basic information." },
      { title: "Start your trial", text: "Download MolarBear and get full access on your clinic computer." },
      { title: "Try it in your clinic", text: "Use MolarBear during your 14-day trial and see how it fits your workflow." },
    ],
    whyTitle: "Don't just hear about it. Try it.",
    whyText: [
      "Every dental clinic has its own workflow.",
      "That's why we're giving you 14 days to experience MolarBear for yourself.",
      "Explore the features, use it with your workflow, and see how it fits your practice.",
    ],
    faqTitle: "Frequently asked questions",
    faq: [
      { q: "Is the trial really free?", a: "Yes. MolarBear includes a 14-day free trial with every feature unlocked." },
      { q: "Do I need a credit card?", a: "No credit card is required to start the trial. You only fill in the short form above." },
      { q: "When does the 14-day trial start?", a: "The 14 days start the first time you open MolarBear on your computer." },
      {
        q: "What happens after 14 days?",
        a: "MolarBear stops saving new records until you activate a licence. Your data stays on your computer. Choose a plan, starting from EGP 15,000 per year, and you continue exactly where you left off.",
      },
      { q: "Can I use MolarBear on my phone?", a: "No. MolarBear is a Windows desktop app for your clinic computers (Windows 10 or 11)." },
      { q: "Is MolarBear only for dentists?", a: "Yes. It is built specifically for dental clinics, from a solo dentist to clinics with several doctors." },
    ],
    finalTitle: "Ready to try MolarBear?",
    finalText: "Get your first 14 days FREE. 🐻",
    byline: "MolarBear by Queue Solutions",
    seePlans: "See plans after the trial",
    otherLanguage: "عربي",
  },
  ar: {
    seoTitle: "MolarBear مجانًا لمدة 14 يومًا | برنامج إدارة عيادات الأسنان | عرض IDC 2026",
    seoDescription:
      "جرّب برنامج MolarBear لإدارة عيادات الأسنان مجانًا لمدة 14 يومًا: المواعيد وسير المرضى ومخطط الأسنان والأشعة والمدفوعات في برنامج ويندوز واحد، دون بطاقة ائتمان.",
    ribbon: "عرض IDC 2026: جرّب برنامج MolarBear لعيادات الأسنان مجانًا لمدة 14 يومًا",
    ribbonCta: "ابدأ تجربتك المجانية",
    headlineTop: "14 يومًا مجانًا",
    headlineBottom: "مع MolarBear",
    heroBadge: "عرض خاص بمناسبة IDC 2026",
    heroKicker: "جرّب MolarBear",
    heroOffer: "14 يومًا مجانًا",
    subheadline: "إدارة عيادة الأسنان أصبحت أبسط.",
    description: "أدِر المرضى والمواعيد والسجلات الطبية والمدفوعات والمخزون وسير العمل اليومي في العيادة من مكان واحد.",
    cta: "ابدأ تجربتي المجانية",
    ctaNote: "14 يومًا مجانًا • دون بطاقة ائتمان",
    noCard: "لا حاجة إلى بطاقة ائتمان.",
    idcTitle: "عرض خاص بمناسبة IDC 2026",
    idcText: "احصل على 14 يومًا من MolarBear مجانًا.",
    idcDates: "7–9 أكتوبر 2026",
    formTitle: "احصل على تجربتك المجانية لمدة 14 يومًا",
    formSubtitle: "أدخل بياناتك لتبدأ استخدام MolarBear.",
    fields: {
      name: "الاسم بالكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الموبايل",
      clinic: "اسم العيادة",
      city: "المدينة",
      optional: "اختياري",
    },
    placeholders: { name: "د. أحمد حسن", clinic: "عيادة سمايل لطب الأسنان", city: "القاهرة" },
    socialTitle: "ابقَ على تواصل",
    socialText: "تابع Queue Solutions لتصلك تحديثات MolarBear والمزايا الجديدة والعروض.",
    socialFacebook: "تابعنا على فيسبوك",
    socialInstagram: "تابعنا على إنستجرام",
    socialHint: "تُفتح صفحتنا في نافذة جديدة.",
    submit: "ابدأ تجربتي المجانية",
    submitting: "جارٍ تجهيز تجربتك...",
    errors: {
      name: "يُرجى إدخال الاسم بالكامل.",
      email: "يُرجى إدخال بريد إلكتروني صحيح.",
      phone: "يُرجى إدخال رقم موبايل صحيح.",
      clinic: "يُرجى إدخال اسم العيادة.",
      submit: "حدث خطأ. حاول مرة أخرى أو راسلنا على واتساب.",
    },
    successTitle: "تجربتك المجانية لمدة 14 يومًا جاهزة!",
    successText: "بدأ التحميل. ثبّت MolarBear على جهاز العيادة لتبدأ.",
    downloadButton: "تحميل MolarBear",
    successFacts: ["مدة التجربة: 14 يومًا", "لا يلزم أي دفع للبدء", "ويندوز 10 أو 11"],
    stepsTitle: "التثبيت في 3 خطوات",
    steps: [
      "افتح ملف MolarBear-Setup.exe واتبع خطوات التثبيت.",
      "إذا ظهرت رسالة ويندوز الزرقاء (SmartScreen)، اضغط «More info» ثم «Run anyway».",
      "افتح MolarBear. تبدأ الأيام الـ 14 من أول مرة تفتح فيها البرنامج.",
    ],
    needHelp: "تحتاج مساعدة في التثبيت؟ راسلنا على واتساب",
    whatsappText: "مرحبًا، قمت بتحميل النسخة التجريبية من MolarBear وأحتاج مساعدة في تشغيلها.",
    fileInfo: "ويندوز 10 أو 11",
    featuresTitle: "ماذا يقدم MolarBear لعيادتك؟",
    features: [
      { icon: "patients", title: "المرضى", text: "بيانات المرضى منظمة وسهلة الوصول." },
      { icon: "calendar", title: "المواعيد", text: "أدِر جدولك والزيارات القادمة." },
      { icon: "tooth", title: "مخطط الأسنان", text: "المعلومات السريرية مرتبطة بملف كل مريض." },
      { icon: "xray", title: "الأشعة والسجلات", text: "الملفات السريرية منظمة ومتاحة في أي وقت." },
      { icon: "payments", title: "المدفوعات", text: "تابع المدفوعات والمعلومات المالية للعيادة." },
      { icon: "inventory", title: "المخزون", text: "تابع مستلزمات العيادة والمخزون." },
    ],
    howTitle: "ابدأ في 3 خطوات بسيطة",
    how: [
      { title: "سجّل بياناتك", text: "أدخل بياناتك الأساسية." },
      { title: "ابدأ التجربة", text: "حمّل MolarBear واحصل على كامل المزايا على جهاز العيادة." },
      { title: "جرّبه في عيادتك", text: "استخدم MolarBear خلال فترة التجربة (14 يومًا) وشاهد كيف يناسب طريقة عملك." },
    ],
    whyTitle: "لا تكتفِ بالسماع عنه. جرّبه.",
    whyText: [
      "لكل عيادة أسنان طريقة عمل خاصة بها.",
      "لذلك نمنحك 14 يومًا لتجرّب MolarBear بنفسك.",
      "استكشف المزايا، واستخدمه وفق طريقة عملك، وشاهد كيف يناسب عيادتك.",
    ],
    faqTitle: "الأسئلة الشائعة",
    faq: [
      { q: "هل التجربة مجانية فعلًا؟", a: "نعم. يتضمن MolarBear فترة تجربة مجانية لمدة 14 يومًا بكل المزايا." },
      { q: "هل أحتاج إلى بطاقة ائتمان؟", a: "لا حاجة إلى بطاقة ائتمان لبدء التجربة. تملأ النموذج القصير أعلاه فقط." },
      { q: "متى تبدأ فترة التجربة (14 يومًا)؟", a: "تبدأ الأيام الـ 14 من أول مرة تفتح فيها MolarBear على جهازك." },
      {
        q: "ماذا يحدث بعد 14 يومًا؟",
        a: "يتوقف MolarBear عن حفظ سجلات جديدة حتى تفعّل الترخيص، وتبقى بياناتك محفوظة على جهازك. اختر باقة تبدأ من 15,000 جنيه سنويًا، وتكمل من حيث توقفت.",
      },
      { q: "هل يمكنني استخدام MolarBear على الموبايل؟", a: "لا. MolarBear برنامج سطح مكتب يعمل على أجهزة العيادة بنظام ويندوز 10 أو 11." },
      { q: "هل MolarBear مخصص لأطباء الأسنان فقط؟", a: "نعم. صُمم خصيصًا لعيادات الأسنان، من الطبيب المستقل حتى العيادات متعددة الأطباء." },
    ],
    finalTitle: "هل أنت مستعد لتجربة MolarBear؟",
    finalText: "احصل على أول 14 يومًا مجانًا. 🐻",
    byline: "MolarBear من Queue Solutions",
    seePlans: "الباقات بعد فترة التجربة",
    otherLanguage: "English",
  },
};
